//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerRankings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameId { get; set; }
        public int SeasonId { get; set; }
        public int Team1Id { get; set; }
        public int Team2Id { get; set; }
        public Nullable<int> Team1Score { get; set; }
        public Nullable<int> Team2Score { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string Location { get; set; }
        public string Comment { get; set; }
        public bool Included { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool Forfeited { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual Season Season { get; set; }
    }
}
