//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerRankings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingDetail
    {
        public int RankingDetailId { get; set; }
        public int RankingEventId { get; set; }
        public int Rank { get; set; }
        public string TeamName { get; set; }
        public decimal PowerRating { get; set; }
        public int Wins { get; set; }
        public int Losses { get; set; }
        public int Ties { get; set; }
        public int PointsFor { get; set; }
        public int PointsAgainst { get; set; }
        public decimal PointsForPerGame { get; set; }
        public decimal PointsAgainstPerGame { get; set; }
        public decimal StrengthOfSchedule { get; set; }
        public bool Deleted { get; set; }
    
        public virtual RankingEvent RankingEvent { get; set; }
    }
}
