//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerRankings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingEvent
    {
        public RankingEvent()
        {
            this.RankingDetails = new HashSet<RankingDetail>();
        }
    
        public int RankingEventId { get; set; }
        public int SeasonId { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<RankingDetail> RankingDetails { get; set; }
        public virtual Season Season { get; set; }
    }
}
